install.packages('rmarkdown')
install.packages('dplyr')
install.packages('knitr')
install.packages("rentrez")
library(rentrez)
ncbi_ids=c("HQ433692.1","HQ433694.1","HQ433691.1")
Bburg=entrez_fetch(db = "nuccore", id = ncbi_ids, rettype = "fasta")
Bburg3=strsplit(Bburg, "\n\n")
Bburg3vec=unlist(Bburg3)
write.csv(Bburg3vec, "Sequences.csv")